# pytorch_lightning==2.0.2
trainer:
  accelerator: gpu
  devices: 1
  logger:
    class_path: pytorch_lightning.loggers.CSVLogger
    init_args:
      save_dir: output
      name: cifar10-linear-lr-0.5
  max_steps: 10000
  val_check_interval: 250
model:
  model_name: vit-b16-224-dino
  training_mode: linear
  optimizer: sgd
  lr: 0.5
  momentum: 0.9
  weight_decay: 0.0
  scheduler: cosine
  warmup_steps: 100
data:
  dataset: cifar10
  root: data/
  size: 224
  batch_size: 128
  workers: 4
model_checkpoint:
  filename: best-step-{step}-{val_acc:.4f}
  monitor: val_acc
  save_last: true
  mode: max
